package routegen

import (
	"strings"
	"testing"

	"github.com/AlmostWorkingSystem/enigma-cli/internal/routescan"
)

func TestCapitalize(t *testing.T) {
	cases := map[string]string{
		"core":    "Core",
		"v1":      "V1",
		"APIView": "Apiview", // matches Python's str.capitalize(): first upper, rest lower
	}
	for in, want := range cases {
		if got := capitalize(in); got != want {
			t.Errorf("capitalize(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestViewName(t *testing.T) {
	got := ViewName("modules.hr.core.api.v1.employee")
	want := "HrCoreV1Employee"
	if got != want {
		t.Fatalf("ViewName = %q, want %q", got, want)
	}
}

func TestViewName_DynamicSegmentsStripBrackets(t *testing.T) {
	got := ViewName("modules.hr.core.api.v1.employee.from_aadhaar.<str:identifier>.verify")
	want := "HrCoreV1EmployeeFromAadhaarStrIdentifierVerify"
	if got != want {
		t.Fatalf("ViewName = %q, want %q", got, want)
	}
}

func TestRender_Eager_StaticAndDynamicRoutes(t *testing.T) {
	routes := []routescan.RouteEntry{
		{URL: "v1/demo/widget/", ModulePath: "modules.demo.api.v1.widget", Name: "widget-list", IsDynamic: false},
		{URL: "v1/demo/widget/<str:identifier>/detail/", ModulePath: "modules.demo.api.v1.widget.<str:identifier>.detail", Name: "", IsDynamic: true},
	}
	out := Render(routes, Eager)

	if !strings.Contains(out, "# This file is auto generated by kit. Do not edit this file manually.\n") {
		t.Fatalf("missing header comment:\n%s", out)
	}
	if !strings.Contains(out, "from modules.demo.api.v1.widget import APIView as DemoV1Widget\n") {
		t.Fatalf("missing static import:\n%s", out)
	}
	if !strings.Contains(out, `    path('v1/demo/widget/', DemoV1Widget.as_view(), name="widget-list"),`+"\n") {
		t.Fatalf("missing static path line:\n%s", out)
	}
	if !strings.Contains(out, `    path('v1/demo/widget/<str:identifier>/detail/', get_api_view('modules.demo.api.v1.widget.<str:identifier>.detail').as_view()),`+"\n") {
		t.Fatalf("missing dynamic path line:\n%s", out)
	}
	for _, line := range strings.Split(out, "\n") {
		if strings.HasPrefix(line, "from ") && strings.Contains(line, "<str:identifier>") {
			t.Fatalf("dynamic route must not get a static import: %s", line)
		}
	}
	if strings.Contains(out, "_LazyAPIView") {
		t.Fatalf("Eager mode must never emit _LazyAPIView:\n%s", out)
	}
	if !strings.HasSuffix(out, "]\n") {
		t.Fatalf("file must end with closing bracket:\n%s", out)
	}
}

func TestRender_Lazy_HeaderDefinesLazyAPIView(t *testing.T) {
	out := Render(nil, Lazy)

	if !strings.HasPrefix(out, "# This file is auto generated by kit. Do not edit this file manually.\n") {
		t.Fatalf("missing header comment:\n%s", out)
	}
	if !strings.Contains(out, "from importlib import import_module\n") {
		t.Fatalf("missing import_module import:\n%s", out)
	}
	if !strings.Contains(out, "from django.urls import path\n") {
		t.Fatalf("missing path import:\n%s", out)
	}
	if !strings.Contains(out, "class _LazyAPIView:\n") {
		t.Fatalf("missing _LazyAPIView class:\n%s", out)
	}
	// .cls must be resolved via __getattr__ (lazy, cached into __dict__),
	// never a @property — drf-spectacular reassigns callback.cls directly.
	if strings.Contains(out, "@property") {
		t.Fatalf("cls must not be a read-only property (drf-spectacular reassigns it):\n%s", out)
	}
	if !strings.Contains(out, `def __getattr__(self, name):`) {
		t.Fatalf("missing __getattr__ for lazy .cls resolution:\n%s", out)
	}
	if !strings.HasSuffix(out, "]\n") {
		t.Fatalf("file must end with closing bracket:\n%s", out)
	}
}

func TestRender_Lazy_EveryRouteUsesLazyAPIView_NoStaticImports(t *testing.T) {
	routes := []routescan.RouteEntry{
		{URL: "v1/demo/widget/", ModulePath: "modules.demo.api.v1.widget", Name: "widget-list", IsDynamic: false},
		{URL: "v1/demo/widget/<str:identifier>/detail/", ModulePath: "modules.demo.api.v1.widget.<str:identifier>.detail", Name: "", IsDynamic: true},
	}
	out := Render(routes, Lazy)

	if !strings.Contains(out, `    path('v1/demo/widget/', _LazyAPIView('modules.demo.api.v1.widget'), name="widget-list"),`+"\n") {
		t.Fatalf("missing static-named route's path line:\n%s", out)
	}
	if !strings.Contains(out, `    path('v1/demo/widget/<str:identifier>/detail/', _LazyAPIView('modules.demo.api.v1.widget.<str:identifier>.detail')),`+"\n") {
		t.Fatalf("missing dynamic-named route's path line:\n%s", out)
	}

	// No per-route static imports at all, for either static- or
	// dynamic-named modules — that's the whole point of this format.
	for _, line := range strings.Split(out, "\n") {
		if strings.HasPrefix(line, "from ") && strings.Contains(line, "import APIView") {
			t.Fatalf("found a static per-route import, should not exist in Lazy mode: %q", line)
		}
	}
}

func TestRender_Lazy_NoNameClauseWhenNameEmpty(t *testing.T) {
	routes := []routescan.RouteEntry{
		{URL: "v1/demo/widget/", ModulePath: "modules.demo.api.v1.widget", Name: ""},
	}
	out := Render(routes, Lazy)

	if strings.Contains(out, "name=") {
		t.Fatalf("unexpected name= clause for a route with no Name:\n%s", out)
	}
	if !strings.Contains(out, `    path('v1/demo/widget/', _LazyAPIView('modules.demo.api.v1.widget')),`+"\n") {
		t.Fatalf("missing expected path line without name clause:\n%s", out)
	}
}

func TestRender_Lazy_EmptyRoutesProducesEmptyURLPatterns(t *testing.T) {
	out := Render(nil, Lazy)
	if !strings.Contains(out, "\nurlpatterns = [\n]\n") {
		t.Fatalf("expected an empty urlpatterns list:\n%s", out)
	}
}
