package routegen

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/AlmostWorkingSystem/enigma-cli/internal/enigmaconfig"
	"github.com/AlmostWorkingSystem/enigma-cli/internal/routescan"
)

// Mode selects how RenderRoutes resolves each route's view class.
type Mode int

const (
	// Eager renders the production format: every route gets a static
	// `from X import Y` (or, for a module path containing "<...>", a
	// module-level get_api_view() call resolved once at import time).
	// Every view module is imported when _routes.py is imported — slower
	// server boot, but nothing needs to be resolved again per-request or
	// for schema generation, since everything is already cached.
	Eager Mode = iota
	// Lazy renders the dev-loop format: every route delegates to a shared
	// _LazyAPIView class that defers importing its view module until
	// either a real request hits it or something (e.g. drf-spectacular's
	// schema generation) introspects .cls. Nothing imports at _routes.py
	// import time — much faster server boot, at the cost of a one-time
	// per-route import on first use instead of at startup.
	Lazy
)

var moduleAPIRe = regexp.MustCompile(`^modules\.(.+)\.api\.(.+)$`)

// capitalize matches Python's str.capitalize(): uppercase the first rune,
// lowercase every subsequent rune. Get this wrong and Eager mode's
// generated import aliases stop matching the real Django-generated
// _routes.py exactly.
func capitalize(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	return strings.ToUpper(string(r[0])) + strings.ToLower(string(r[1:]))
}

// ViewName ports get_api_from_module_path (kit/views/helpers.py:98-126) —
// only used by Eager mode, to name each route's static import alias.
func ViewName(module string) string {
	m := moduleAPIRe.FindStringSubmatch(module)
	if m == nil {
		return capitalize(strings.ReplaceAll(module, ".", ""))
	}
	modulePart, pathPart := m[1], m[2]

	replaced := strings.NewReplacer(":", ".", "_", ".").Replace(pathPart)
	parts := strings.Split(replaced, ".")

	var b strings.Builder
	for _, mod := range strings.Split(modulePart, ".") {
		b.WriteString(capitalize(mod))
	}
	for _, p := range parts {
		stripped := strings.NewReplacer("<", "", ">", "").Replace(p)
		b.WriteString(capitalize(stripped))
	}
	return b.String()
}

// lazyAPIViewClass is Lazy mode's view-loading class: every route's
// path() delegates to it instead of a static import. Every route
// (static-named or dynamic-<type:name>-named alike) is emitted the same
// way — there's no static `from X import Y` per route, so nothing imports
// any view module at _routes.py import time. _LazyAPIView defers that
// until either a real request hits the route (__call__) or something
// introspects .cls (e.g. drf-spectacular's schema generation, which reads
// AND reassigns callback.cls — see EndpointEnumerator in drf_spectacular's
// generators.py — so .cls must stay a plain writable attribute, not a
// read-only property; __getattr__ resolves it once and caches it into
// __dict__, after which normal attribute get/set semantics apply).
const lazyAPIViewClass = `

class _LazyAPIView:
    def __init__(self, module):
        self.module = module
        self.initkwargs = {}
        self._view = None

    def _load(self):
        if self._view is None:
            mod = import_module(self.module)
            cls = getattr(mod, "APIView")
            self.__dict__["cls"] = cls
            self._view = cls.as_view()
        return self._view

    def __call__(self, request, *args, **kwargs):
        return self._load()(request, *args, **kwargs)

    def __getattr__(self, name):
        if name == "cls":
            self._load()
            return self.__dict__["cls"]
        raise AttributeError(name)
`

// RenderRoutes produces _routes.py content in the given Mode. It is
// imported by config/urls.py, well after django.setup() has populated the
// app registry — Eager mode's per-route static imports (and its
// get_api_view helper's `from kit.views.base import BaseAPIView`) reach
// real Django model classes transitively, which is only safe once
// django.setup() has already run. See RenderConfig's doc comment for why
// this must stay a separate file/import from INSTALLED_APPS/ENIGMA_CONFIG,
// which are needed *before* django.setup().
func RenderRoutes(routes []routescan.RouteEntry, mode Mode) string {
	if mode == Lazy {
		return renderLazyRoutes(routes)
	}
	return renderEagerRoutes(routes)
}

func renderLazyRoutes(routes []routescan.RouteEntry) string {
	var urls strings.Builder
	for _, r := range routes {
		nameClause := ""
		if r.Name != "" {
			nameClause = fmt.Sprintf(`, name="%s"`, r.Name)
		}
		urls.WriteString(fmt.Sprintf("    path('%s', _LazyAPIView('%s')%s),\n", r.URL, r.ModulePath, nameClause))
	}

	var out strings.Builder
	out.WriteString("# This file is auto generated by kit. Do not edit this file manually.\n")
	out.WriteString("# Python extension is required in order to Cmd + Click to navigate to view class.\n")
	out.WriteString("\nfrom importlib import import_module\nfrom django.urls import path\n")
	out.WriteString(lazyAPIViewClass)
	out.WriteString("\nurlpatterns = [\n")
	out.WriteString(urls.String())
	out.WriteString("]\n")
	return out.String()
}

// renderEagerRoutes matches Config.save_urls (kit/conf/config.py:267-315)
// byte-for-byte in shape — this is the format the real Django-generated
// _routes.py already uses in production.
func renderEagerRoutes(routes []routescan.RouteEntry) string {
	var imports strings.Builder
	imports.WriteString("\nfrom importlib import import_module\nfrom django.urls import path\nfrom kit.views.base import BaseAPIView\nfrom typing import cast\n")

	var urls strings.Builder
	for _, r := range routes {
		nameClause := ""
		if r.Name != "" {
			nameClause = fmt.Sprintf(`, name="%s"`, r.Name)
		}
		if r.IsDynamic {
			urls.WriteString(fmt.Sprintf("    path('%s', get_api_view('%s').as_view()%s),\n", r.URL, r.ModulePath, nameClause))
			continue
		}
		view := ViewName(r.ModulePath)
		imports.WriteString(fmt.Sprintf("from %s import APIView as %s\n", r.ModulePath, view))
		urls.WriteString(fmt.Sprintf("    path('%s', %s.as_view()%s),\n", r.URL, view, nameClause))
	}

	var out strings.Builder
	out.WriteString("# This file is auto generated by kit. Do not edit this file manually.\n")
	out.WriteString("# Python extension is required in order to Cmd + Click to navigate to view class.\n")
	out.WriteString(imports.String())
	out.WriteString("\n\ndef get_api_view(module: str):\n    _module = import_module(\n            module\n    )\n    return cast(BaseAPIView, getattr(_module, \"APIView\", None))\n")
	out.WriteString("\nurlpatterns = [\n")
	out.WriteString(urls.String())
	out.WriteString("]\n")
	return out.String()
}

// RenderConfig produces _enigma.py content: INSTALLED_APPS and
// ENIGMA_CONFIG only, deliberately with zero Django imports anywhere in
// the file. This is imported by kit/conf/__init__.py's initialize_conf()
// *before* django.setup() runs (Django requires INSTALLED_APPS to be set
// before the app registry populates) — a file that transitively imported
// anything Model-shaped (as RenderRoutes's Eager mode does, via
// kit.views.base) would crash with AppRegistryNotReady at that point,
// since app registry population is exactly what hasn't happened yet. This
// is why routes and config live in separate generated files rather than
// one unified one, despite both being derived from the same
// enigmaconfig.Config: they have mutually exclusive import-time
// constraints (config must import before django.setup(); Eager-mode
// routes must import after it).
func RenderConfig(cfg *enigmaconfig.Config) string {
	var out strings.Builder
	out.WriteString("# This file is auto generated by kit. Do not edit this file manually.\n")
	out.WriteString("# Python extension is required in order to Cmd + Click to navigate to view class.\n")
	out.WriteString(configClasses)

	out.WriteString("\nINSTALLED_APPS = [\n")
	for _, app := range installedApps(cfg) {
		out.WriteString(fmt.Sprintf("    %q,\n", app))
	}
	out.WriteString("]\n")

	out.WriteString("\nENIGMA_CONFIG = _EnigmaConfig(modules={\n")
	renderConfigModules(cfg, &out)
	out.WriteString("})\n")
	return out.String()
}

// configClasses defines the two tiny, dependency-free classes ENIGMA_CONFIG
// is built from. They exist purely so kit/conf/functions.py's existing
// `config.modules["hr"].submodules` / `module.name` attribute-access style
// keeps working unchanged against the generated data — no Django or
// pydantic import is needed to read this file, unlike the classes in
// kit/conf/config.py they replace at server-boot time.
const configClasses = `

class _ConfigModule:
    __slots__ = ("name", "submodules")

    def __init__(self, name, submodules):
        self.name = name
        self.submodules = submodules


class _EnigmaConfig:
    __slots__ = ("modules",)

    def __init__(self, modules):
        self.modules = modules
`

// installedApps ports Module.populate's app-discovery shape
// (kit/conf/config.py:61-75) into plain dotted-string paths — Django's own
// apps.populate() constructs the real AppConfig instances from these
// strings itself (it always does, even for the pre-built-instance form the
// current Python ConfigParser uses), so nothing here needs django.apps.
func installedApps(cfg *enigmaconfig.Config) []string {
	var apps []string
	for _, me := range cfg.Modules {
		if me.Module.Settings.Standalone {
			apps = append(apps, "modules."+me.Name)
			continue
		}
		for _, se := range me.Module.Submodules {
			apps = append(apps, fmt.Sprintf("modules.%s.%s", me.Name, se.Name))
		}
	}
	return apps
}

// renderConfigModules writes ENIGMA_CONFIG's modules dict literal, matching
// exactly what kit/conf/functions.py's has_submodule/get_submodule_list
// need: each module's name and its submodules' names (never api_versions,
// standalone, or anything AppConfig/URL-resolver-shaped).
func renderConfigModules(cfg *enigmaconfig.Config, out *strings.Builder) {
	for _, me := range cfg.Modules {
		out.WriteString(fmt.Sprintf("    %q: _ConfigModule(%q, submodules={\n", me.Name, me.Name))
		for _, se := range me.Module.Submodules {
			out.WriteString(fmt.Sprintf("        %q: _ConfigModule(%q, submodules={}),\n", se.Name, se.Name))
		}
		out.WriteString("    }),\n")
	}
}
