package routegen

import (
	"strings"
	"testing"

	"github.com/AlmostWorkingSystem/enigma-cli/internal/routescan"
)

func TestCapitalize(t *testing.T) {
	cases := map[string]string{
		"core":    "Core",
		"v1":      "V1",
		"APIView": "Apiview", // matches Python's str.capitalize(): first upper, rest lower
	}
	for in, want := range cases {
		if got := capitalize(in); got != want {
			t.Errorf("capitalize(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestViewName(t *testing.T) {
	got := ViewName("modules.hr.core.api.v1.employee")
	want := "HrCoreV1Employee"
	if got != want {
		t.Fatalf("ViewName = %q, want %q", got, want)
	}
}

func TestViewName_DynamicSegmentsStripBrackets(t *testing.T) {
	got := ViewName("modules.hr.core.api.v1.employee.from_aadhaar.<str:identifier>.verify")
	want := "HrCoreV1EmployeeFromAadhaarStrIdentifierVerify"
	if got != want {
		t.Fatalf("ViewName = %q, want %q", got, want)
	}
}

func TestRender_StaticAndDynamicRoutes(t *testing.T) {
	routes := []routescan.RouteEntry{
		{URL: "v1/demo/widget/", ModulePath: "modules.demo.api.v1.widget", Name: "widget-list", IsDynamic: false},
		{URL: "v1/demo/widget/<str:identifier>/detail/", ModulePath: "modules.demo.api.v1.widget.<str:identifier>.detail", Name: "", IsDynamic: true},
	}
	out := Render(routes)

	if !strings.Contains(out, "# This file is auto generated by kit. Do not edit this file manually.\n") {
		t.Fatalf("missing header comment:\n%s", out)
	}
	if !strings.Contains(out, "from modules.demo.api.v1.widget import APIView as DemoV1Widget\n") {
		t.Fatalf("missing static import:\n%s", out)
	}
	if !strings.Contains(out, `    path('v1/demo/widget/', DemoV1Widget.as_view(), name="widget-list"),`+"\n") {
		t.Fatalf("missing static path line:\n%s", out)
	}
	if !strings.Contains(out, `    path('v1/demo/widget/<str:identifier>/detail/', get_api_view('modules.demo.api.v1.widget.<str:identifier>.detail').as_view()),`+"\n") {
		t.Fatalf("missing dynamic path line:\n%s", out)
	}
	if strings.Contains(out, "import APIView as ") && strings.Contains(out, "widget.<str:identifier>.detail") {
		// the dynamic route's module path must never appear in a static import line
		for _, line := range strings.Split(out, "\n") {
			if strings.HasPrefix(line, "from ") && strings.Contains(line, "<str:identifier>") {
				t.Fatalf("dynamic route must not get a static import: %s", line)
			}
		}
	}
	if !strings.HasSuffix(out, "]\n") {
		t.Fatalf("file must end with closing bracket:\n%s", out)
	}
}
