package routegen

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/AlmostWorkingSystem/enigma-cli/internal/routescan"
)

// Mode selects how Render resolves each route's view class.
type Mode int

const (
	// Eager renders the production format: every route gets a static
	// `from X import Y` (or, for a module path containing "<...>", a
	// module-level get_api_view() call resolved once at import time).
	// Every view module is imported when _routes.py is imported — slower
	// server boot, but nothing needs to be resolved again per-request or
	// for schema generation, since everything is already cached.
	Eager Mode = iota
	// Lazy renders the dev-loop format: every route delegates to a shared
	// _LazyAPIView class that defers importing its view module until
	// either a real request hits it or something (e.g. drf-spectacular's
	// schema generation) introspects .cls. Nothing imports at _routes.py
	// import time — much faster server boot, at the cost of a one-time
	// per-route import on first use instead of at startup.
	Lazy
)

var moduleAPIRe = regexp.MustCompile(`^modules\.(.+)\.api\.(.+)$`)

// capitalize matches Python's str.capitalize(): uppercase the first rune,
// lowercase every subsequent rune. Get this wrong and Eager mode's
// generated import aliases stop matching the real Django-generated
// _routes.py exactly.
func capitalize(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	return strings.ToUpper(string(r[0])) + strings.ToLower(string(r[1:]))
}

// ViewName ports get_api_from_module_path (kit/views/helpers.py:98-126) —
// only used by Eager mode, to name each route's static import alias.
func ViewName(module string) string {
	m := moduleAPIRe.FindStringSubmatch(module)
	if m == nil {
		return capitalize(strings.ReplaceAll(module, ".", ""))
	}
	modulePart, pathPart := m[1], m[2]

	replaced := strings.NewReplacer(":", ".", "_", ".").Replace(pathPart)
	parts := strings.Split(replaced, ".")

	var b strings.Builder
	for _, mod := range strings.Split(modulePart, ".") {
		b.WriteString(capitalize(mod))
	}
	for _, p := range parts {
		stripped := strings.NewReplacer("<", "", ">", "").Replace(p)
		b.WriteString(capitalize(stripped))
	}
	return b.String()
}

// lazyHeader is Lazy mode's fixed preamble: imports plus the _LazyAPIView
// class every route's path() delegates to. Every route (static-named or
// dynamic-<type:name>-named alike) is emitted the same way — there's no
// static `from X import Y` per route, so nothing imports any view module
// at _routes.py import time. _LazyAPIView defers that until either a real
// request hits the route (__call__) or something introspects .cls (e.g.
// drf-spectacular's schema generation, which reads AND reassigns
// callback.cls — see EndpointEnumerator in drf_spectacular's
// generators.py — so .cls must stay a plain writable attribute, not a
// read-only property; __getattr__ resolves it once and caches it into
// __dict__, after which normal attribute get/set semantics apply).
const lazyHeader = `# This file is auto generated by kit. Do not edit this file manually.
# Python extension is required in order to Cmd + Click to navigate to view class.

from importlib import import_module
from django.urls import path


class _LazyAPIView:
    def __init__(self, module):
        self.module = module
        self.initkwargs = {}
        self._view = None

    def _load(self):
        if self._view is None:
            mod = import_module(self.module)
            cls = getattr(mod, "APIView")
            self.__dict__["cls"] = cls
            self._view = cls.as_view()
        return self._view

    def __call__(self, request, *args, **kwargs):
        return self._load()(request, *args, **kwargs)

    def __getattr__(self, name):
        if name == "cls":
            self._load()
            return self.__dict__["cls"]
        raise AttributeError(name)
`

// Render produces _routes.py content in the given Mode.
func Render(routes []routescan.RouteEntry, mode Mode) string {
	if mode == Lazy {
		return renderLazy(routes)
	}
	return renderEager(routes)
}

func renderLazy(routes []routescan.RouteEntry) string {
	var urls strings.Builder
	for _, r := range routes {
		nameClause := ""
		if r.Name != "" {
			nameClause = fmt.Sprintf(`, name="%s"`, r.Name)
		}
		urls.WriteString(fmt.Sprintf("    path('%s', _LazyAPIView('%s')%s),\n", r.URL, r.ModulePath, nameClause))
	}

	var out strings.Builder
	out.WriteString(lazyHeader)
	out.WriteString("\nurlpatterns = [\n")
	out.WriteString(urls.String())
	out.WriteString("]\n")
	return out.String()
}

// renderEager matches Config.save_urls (kit/conf/config.py:267-315)
// byte-for-byte in shape — this is the format the real Django-generated
// _routes.py already uses in production.
func renderEager(routes []routescan.RouteEntry) string {
	var imports strings.Builder
	imports.WriteString("\nfrom importlib import import_module\nfrom django.urls import path\nfrom kit.views.base import BaseAPIView\nfrom typing import cast\n")

	var urls strings.Builder
	for _, r := range routes {
		nameClause := ""
		if r.Name != "" {
			nameClause = fmt.Sprintf(`, name="%s"`, r.Name)
		}
		if r.IsDynamic {
			urls.WriteString(fmt.Sprintf("    path('%s', get_api_view('%s').as_view()%s),\n", r.URL, r.ModulePath, nameClause))
			continue
		}
		view := ViewName(r.ModulePath)
		imports.WriteString(fmt.Sprintf("from %s import APIView as %s\n", r.ModulePath, view))
		urls.WriteString(fmt.Sprintf("    path('%s', %s.as_view()%s),\n", r.URL, view, nameClause))
	}

	var out strings.Builder
	out.WriteString("# This file is auto generated by kit. Do not edit this file manually.\n")
	out.WriteString("# Python extension is required in order to Cmd + Click to navigate to view class.\n")
	out.WriteString(imports.String())
	out.WriteString("\n\ndef get_api_view(module: str):\n    _module = import_module(\n            module\n    )\n    return cast(BaseAPIView, getattr(_module, \"APIView\", None))\n")
	out.WriteString("\nurlpatterns = [\n")
	out.WriteString(urls.String())
	out.WriteString("]\n")
	return out.String()
}
