package routegen

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/AlmostWorkingSystem/enigma-cli/internal/routescan"
)

var moduleAPIRe = regexp.MustCompile(`^modules\.(.+)\.api\.(.+)$`)

// capitalize matches Python's str.capitalize(): uppercase the first rune,
// lowercase every subsequent rune. Get this wrong and generated import
// aliases stop matching the current _routes.py exactly.
func capitalize(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	return strings.ToUpper(string(r[0])) + strings.ToLower(string(r[1:]))
}

// ViewName ports get_api_from_module_path (kit/views/helpers.py:98-126).
func ViewName(module string) string {
	m := moduleAPIRe.FindStringSubmatch(module)
	if m == nil {
		return capitalize(strings.ReplaceAll(module, ".", ""))
	}
	modulePart, pathPart := m[1], m[2]

	replaced := strings.NewReplacer(":", ".", "_", ".").Replace(pathPart)
	parts := strings.Split(replaced, ".")

	var b strings.Builder
	for _, mod := range strings.Split(modulePart, ".") {
		b.WriteString(capitalize(mod))
	}
	for _, p := range parts {
		stripped := strings.NewReplacer("<", "", ">", "").Replace(p)
		b.WriteString(capitalize(stripped))
	}
	return b.String()
}

// Render produces _routes.py content, matching Config.save_urls
// (kit/conf/config.py:267-315) byte-for-byte in shape.
func Render(routes []routescan.RouteEntry) string {
	var imports strings.Builder
	imports.WriteString("\nfrom importlib import import_module\nfrom django.urls import path\nfrom kit.views.base import BaseAPIView\nfrom typing import cast\n")

	var urls strings.Builder
	for _, r := range routes {
		nameClause := ""
		if r.Name != "" {
			nameClause = fmt.Sprintf(`, name="%s"`, r.Name)
		}
		if r.IsDynamic {
			urls.WriteString(fmt.Sprintf("    path('%s', get_api_view('%s').as_view()%s),\n", r.URL, r.ModulePath, nameClause))
			continue
		}
		view := ViewName(r.ModulePath)
		imports.WriteString(fmt.Sprintf("from %s import APIView as %s\n", r.ModulePath, view))
		urls.WriteString(fmt.Sprintf("    path('%s', %s.as_view()%s),\n", r.URL, view, nameClause))
	}

	var out strings.Builder
	out.WriteString("# This file is auto generated by kit. Do not edit this file manually.\n")
	out.WriteString("# Python extension is required in order to Cmd + Click to navigate to view class.\n")
	out.WriteString(imports.String())
	out.WriteString("\n\ndef get_api_view(module: str):\n    _module = import_module(\n            module\n    )\n    return cast(BaseAPIView, getattr(_module, \"APIView\", None))\n")
	out.WriteString("\nurlpatterns = [\n")
	out.WriteString(urls.String())
	out.WriteString("]\n")
	return out.String()
}
